version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - '8080'
    volumes:
      - ./api:/app
    depends_on:
      - db
    environment:
      APP_SECRET: ${APP_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      

      DEFAULT_USER_NAME: ${DEFAULT_USER_NAME}
      DEFAULT_USER_EMAIL: ${DEFAULT_USER_EMAIL}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}

  view:
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./view:/app

  db:
    image: mariadb
    restart: always
    volumes:
      - ./api/migrations:/docker-entrypoint-initdb.d
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3308:3306'
    expose:
      - '3306'
